# Generated by Django 2.2 on 2020-08-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='date',
            field=models.DateField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='time',
            field=models.TimeField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='content',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
